### ISSUE TITLE
What is the requirement of tensorflow version?

### ISSUE THREAD

**Issue by sydat2701** [srijandas07/VPN#10]
I can not import layer 'Merge' from 'keras.layers' like in your code. I have tried some different versions of tensorflow (v1, v2,...), but it still doesn't work.

**Comment by srijandas07** [comment]
Hi 
These are requirements - 
python 3.6.8
Tensorflow 1.13.0 (GPU compatible)
keras 2.3.1

May be now the Merge layer is removed with Add, or concatenate layers. You can try them out too.
