### ISSUE TITLE
Question about discrepancy with the published paper 

### ISSUE THREAD

**Issue by chewry** [srijandas07/VPN#2]
First of all, thank you for sharing your good research.
For the spatial embedding, the Euclidean distance of the L2 normalized feature is used in the paper.
But [the code](https://github.com/srijandas07/VPN/blob/db0243d0d6174812903d3b4d178db9609a5f4327/embedding_gcnn_attention_model.py#L38) on repository uses Manhatten distance.
I'd like to know if these changes are intended and what difference the changed metrics make.

Thank you in advance.

**Comment by srijandas07** [comment]
Hi @chewry 
Thanks for your interest in our work.
Please note that we have invoked two lossess, one explicitly for the embedding with ground truth as zeros. On the other hand, we use a lambda layer to compute the absolute difference between the features. So by using mse loss, you can compute the Euclidean between them in a hacky way.
Note that you can use a normalized term in the loss but that won't change the performance. 
Hope this helps!

**Comment by chewry** [comment]
Thank you for your kind reply. 
However, my question has not been resolved completely.

In order to get the Euclidean distance through MSE, I think the dimension size must be maintained without summation in [that code line](https://github.com/srijandas07/VPN/blob/db0243d0d6174812903d3b4d178db9609a5f4327/embedding_gcnn_attention_model.py#L38).
Please let me know if I'm misunderstood.

**Comment by srijandas07** [comment]
Yes, true. In that case, you need to replicate the GT to the correct dimension size and your model training time would increase. Here, we provided the simplest and a light weighted mechanism to train the model. In fact, we have also removed the non zero constraints from this code.
For this embedding, you are free to use any loss minimizing the distance between these features.
I will update the README with your remarks (as a warning!) perhaps.

**Comment by chewry** [comment]
Thanks again for your detailed answer and nice work!
My question has been resolved and I close the issue now.
