### ISSUE TITLE
Question about the Smarthome dataset

### ISSUE THREAD

**Issue by punknownq** [srijandas07/VPN#4]
Hi, thank you for your good job. I am using the Smarthome dataset now. Could you tell me the specific 19 activities in CV1 and CV2?

**Comment by srijandas07** [comment]
@punknownq please refer to fig. 3 & 4 in https://openaccess.thecvf.com/content_ICCV_2019/supplemental/Das_Toyota_Smarthome_Real-World_ICCV_2019_supplemental.pdf

**Comment by punknownq** [comment]
Thank you for your reply.
