### ISSUE TITLE
Data Normalization

### ISSUE THREAD

**Issue by MDuc-ai** [srijandas07/VPN#5]
Hi, I am trying to train NTU with your model but your code does not mention how the poses' x, y, z are normalized. Could you give me your normalization method.

**Comment by srijandas07** [comment]
@tranminhduc4796 a very good data normalization of the poses is performed in https://github.com/lshiwjx/2s-AGCN
In our case, we just perform a body translation with the hips (already in the Loader). We do not perform any other normalization.

**Comment by MDuc-ai** [comment]
Thanks. I also have another suspicious and hope you can confirm it for me. A npy file you mentioned contain a matrix represent **2 poses** in a single video so each has a size of n_frames x 150 (25 joints x 3 coords x 2 people). Is my understanding right?

**Comment by srijandas07** [comment]
Yes, absolutely the matrix represents 2 poses. In case, there is a single person in a video, we pad the last 75 elements with zeros.

**Comment by MDuc-ai** [comment]
Thank you for all of your supports.
