### ISSUE TITLE
How can I convert NTU dataset into patches_full_body

### ISSUE THREAD

**Issue by ale152** [srijandas07/VPN#8]
Hello there!

Thank you for sharing this great piece of research! I was trying to train the model from scratch, so I downloaded the NTU dataset from the official website. Your code requires the dataset to be in the form of images cropped around the human patches (in the folder "patches_full_body"), could you please share the script that generates these cropped images to make sure that I'm doing everything in the exact same way as the paper? How are the patches generated and how do you deal with multiple people in the scene?

Thank you

**Comment by srijandas07** [comment]
Hello @ale152 
You can simply make use of the 2D skeletons provided in the NTU dataset to extract the patches.
I have generated the patches by running SSD on the entire dataset and extracting the human bounding boxes. For images with two people, I had considered extracting the bounding box wrt the person with more motion (can be evaluated from the skeleton information). However, a better approach would be to extract the patches covering both the person.
Note: Don't forget to give some slack space around the bounding box to make sure you don't miss any contextually important information.
